{{- $fullName := include "aquatic-tracker.fullname" . -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "aquatic-tracker.labels" . | nindent 4 }}
  {{- with .Values.configmap.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end}}
data:
  udp: |-
    {{ .Files.Get "etc/udp.toml" | nindent 4 }}
  ws: |-
    {{ .Files.Get "etc/ws.toml" | nindent 4 }}
  http: |-
    {{ .Files.Get "etc/http.toml" | nindent 4}}
