socket_workers = 1
request_workers = 1
log_level = 'error'

[network]
address = '0.0.0.0:3000'
max_scrape_torrents = 255
max_response_peers = 255
peer_announce_interval = 900
socket_recv_buffer_size = 524288
poll_event_capacity = 4096

[handlers]
max_requests_per_iter = 10000
channel_recv_timeout_microseconds = 200

[statistics]
interval = 5

[cleaning]
interval = 30
max_peer_age = 1200
max_connection_age = 300

[privileges]
drop_privileges = false
chroot_path = '.'
user = 'nobody'
