socket_workers = 1
log_level = 'error'

[network]
address = '0.0.0.0:3000'
ipv6_only = false
use_tls = false
tls_pkcs12_path = ''
tls_pkcs12_password = ''
max_scrape_torrents = 255
max_offers = 10
peer_announce_interval = 120
poll_event_capacity = 4096
poll_timeout_milliseconds = 50
websocket_max_message_size = 65536
websocket_max_frame_size = 16384

[handlers]
max_requests_per_iter = 10000
channel_recv_timeout_microseconds = 200

[cleaning]
interval = 30
max_peer_age = 180
max_connection_age = 180

[privileges]
drop_privileges = false
chroot_path = '.'
user = 'nobody'
